Add manner to fix odom2base by adding outside odometry.
rm-controls/rm_controllers pull request #115
Opened 2023-03-16 15:31 UTC by Edwinlinks

添加了使用外部里程计去更新odom2base的方式

2023-03-16 15:41 UTC, ye-luo-xi-tui approved these changes

2023-03-17 02:20 UTC, qiayuanliao requested changes
其实我一直在纠结 world2sensor 的 world 叫什么好一点，因为那个是 sensor 的world frame 而不是所有人的

2023-03-17 02:20 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +      controller_nh.subscribe<nav_msgs::Odometry>("/Odometry", 10, &ChassisBase::outsideOdomCallback, this);
不可能有 topic 名字是 首字母大写！

2023-03-17 02:20 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +    if (world2odom_.getRotation() == tf2::Quaternion::getIdentity())
我的注释咋被删了

2023-03-18 11:52 UTC, Edwinlinks commented
> 其实我一直在纠结 world2sensor 的 world 叫什么好一点，因为那个是 sensor 的world frame 而不是所有人的

这个的话我也有想过，但是没有什么好建议，后面又想到我们导航的世界坐标系是 map ，和 world 有区别所以暂时觉得可以用，后面我有想到的话会提交 pr

2023-03-21 08:02 UTC, ye-luo-xi-tui commented
> > 其实我一直在纠结 world2sensor 的 world 叫什么好一点，因为那个是 sensor 的world frame 而不是所有人的
> 
> 这个的话我也有想过，但是没有什么好建议，后面又想到我们导航的世界坐标系是 map ，和 world 有区别所以暂时觉得可以用，后面我有想到的话会提交 pr

@qiayuanliao

2023-03-21 10:27 UTC, merged