Add multi_dof_controller.
rm-controls/rm_controllers pull request #122
Opened 2023-03-29 09:37 UTC by L-SY

## Pr目的：

 增加新的控制器方便翻转接入到动作组之间。

### 功能说明：

 控制器有两个state，可以选择速度控制和位置控制。其中位置控制目的为了让矿石转动指定的角度或者长度。

### 配套参数文件：
```
  multi_dof_controller:
    type: multi_dof_controller/Controller
    joints:
      pitch_front_joint:
        position:
          joint: pitch_front_joint
          pid: { p: 0.02, i: 0., d: 0.1, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
        velocity:
          joint: pitch_front_joint
          pid: { p: 0.02, i: 0., d: 0, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }m
   motions:
      angular_y:
        velocity: [1.,1.,1.,1.]
        velocity_max_speed: 5
        position: [1.,1.,1.,1.]
        position_per_step: 1
        fixed_direction: [0,0,0,0]
  calibrated: true
```
#### 参数说明：

-  joints:控制器用到的电机，可以变化数量，初始化内容放到.h中JOINTS结构体中
-  motions:控制器包含的动作名称（可包括x,y,z,r,p,y)初始化内容放到.h中MOTIONS结构体中
-  velocity:单个动作的电机速度配置（大小方向）
-  fixed_direction：考虑到某些动作下，有些电机仅仅为辅助作用，旋转方向固定，不因输入值而改变（例如目前工程 pitch翻转时候，下层的两个电机同向转动来翻动pitch，上层两个电机持续往下让矿石吃到下面两个电机的摩擦力）
-  position_per_step：位置控制下，每一步转的度数或距离（对应到 position_config中每一个电机为了让矿石转这一步自身需要转动的角度。

### 目前情况：

 电机组按指定的速度转和转指定到的位置经过测试暂时没发现问题。

### 改进的方向：

1. 找到一些遗漏的会出错的地方
2. 删除不必要的代码
3. 是否需要加入视觉模式（或者在conmandsender中间加）

2023-03-29 09:40 UTC, L-SY commented
不好意思之前pr由于错误操作关闭了。
CI未过的原因：对应的消息类型还未通过 https://github.com/rm-controls/rm_control/pull/122/files

2023-04-10 15:31 UTC, qiayuanliao commented
@ye-luo-xi-tui 他不是还没搞完嘛（消息类型改完之后还得改这个pr）。摇头摇头摇头。

2023-04-10 15:42 UTC, qiayuanliao requested changes
is_need_reverse_  改为 direction_ 或 dir_ 。rm_hw 有类似的东西命名，为啥要自己编一个而且还很诡异 is_need ...

position_config 和 velocity_config 去掉 config

@ye-luo-xi-tui 发现了很多小问题。review 质量极低。reviewer 会不会太少？

希望 review 能力能得到锻炼和进步，又快又准地读懂别人的代码+定位问题和缺陷也是一种重要的能力~

2023-04-11 00:40 UTC, L-SY commented
> > 不好意思之前pr由于错误操作关闭了。 CI未过的原因：对应的消息类型还未通过 https://github.com/rm-controls/rm_control/pull/122/files
> 
> 这个 pr 咋还没改？

现在已经对应修改好了

2023-04-11 00:46 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +}
这个是为了让某些辅助的电机的旋转方向不随输入值改变。（例如目前工程 pitch翻转时候，下层的两个电机同向转动来翻动pitch，上层两个电机（辅助电机）持续往下让矿石吃到下面两个电机的摩擦力），这个感觉和rm_hw那个有区别，有时候一些自己觉得简单的就没想着参考代码了，以后会注意。

2023-04-11 00:48 UTC, L-SY commented
> > ## Pr目的：
> > 增加新的控制器方便翻转接入到动作组之间。
> > ### 功能说明：
> > 控制器有两个state，可以选择速度控制和位置控制。其中位置控制目的为了让矿石转动指定的角度或者长度。
> > ### 配套参数文件：
> > ```
> >   multi_dof_controller:
> >     type: multi_dof_controller/Controller
> >     joints:
> >       pitch_front_joint:
> >         position:
> >           joint: pitch_front_joint
> >           pid: { p: 0.02, i: 0., d: 0.1, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }
> >         velocity:
> >           joint: pitch_front_joint
> >           pid: { p: 0.02, i: 0., d: 0, i_clamp_max: 0., i_clamp_min: 0., antiwindup: true, publish_state: true }m
> >    motions:
> >       pitch:
> >       velocity_config: [1.,1.,1.,1.]
> >       velocity_max_speed: 5
> >       position_config: [1.,1.,1.,1.]
> >       position_per_step: 1
> >       is_need_reverse: [0,0,0,0]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 参数说明：
> > 
> > * joints:控制器用到的电机，可以变化数量，初始化内容放到.h中JOINTS结构体中
> > * motions:控制器包含的动作名称（可包括x,y,z,r,p,y)初始化内容放到.h中MOTIONS结构体中
> > * velocity_config:单个动作的电机速度配置（大小方向）
> > * is_velocity_need_reverse：考虑到某些动作下，有些电机仅仅为辅助作用，旋转方向固定，不因输入值而改变（例如目前工程 pitch翻转时候，下层的两个电机同向转动来翻动pitch，上层两个电机持续往下让矿石吃到下面两个电机的摩擦力）
> > * position_per_step：位置控制下，每一步转的度数或距离（对应到 position_config中每一个电机为了让矿石转这一步自身需要转动的角度。
> > 
> > ### 目前情况：
> > 电机组按指定的速度转和转指定到的位置经过测试暂时没发现问题。
> > ### 改进的方向：
> > 
> > 1. 找到一些遗漏的会出错的地方
> > 2. 删除不必要的代码
> > 3. 是否需要加入视觉模式（或者在conmandsender中间加）
> 
> 你的配置文件示例确定没有写错吗？

确实写错了，之前没有及时更改，现在已改。

2023-04-11 00:51 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +}
这个还是有点用的吧，目的是为了最后results赋值的部分看起来不加入判断（感觉连贯一点）
```
results[i] += judgeReverse(motion_group_values_[j], motions_[k].is_need_reverse_[i]) 
*motions_[k].velocity_max_speed_ * motions_[k].velocity_config_[i];
```

2023-04-11 00:56 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  robot_state_handle_ = robot_hw->get<rm_control::RobotStateInterface>()->getHandle("robot_state");
确实没用，已删除。
之前参照gimbal_controller和chassis_controller(舵轮)写的初始化，想着有可能有用就保留了，但是其实没地方会用到坐标系转化确实多余。

2023-04-11 01:03 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  if (arrived_joint_num == (int)joints_.size() || (ros::Time::now() - start_time_).toSec() >= time_out_)
确实，蠢了，以改正。

2023-04-11 01:03 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +    start_time_ = ros::Time::now();
已改正。

2023-04-11 16:12 UTC, qiayuanliao commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  robot_state_handle_ = robot_hw->get<rm_control::RobotStateInterface>()->getHandle("robot_state");
@ye-luo-xi-tui 出来挨打哈哈哈

2023-04-11 16:13 UTC, qiayuanliao commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  robot_state_handle_ = robot_hw->get<rm_control::RobotStateInterface>()->getHandle("robot_state");
而且你这个地方没用到 clion 绝对有提示。

另外你别天天说什么以后要用，要用再加。

2023-04-11 16:25 UTC, qiayuanliao commented
> > is_need_reverse_ 改为 direction_ 或 dir_ 。rm_hw 有类似的东西命名，为啥要自己编一个而且还很诡异 is_need ...
> > position_config 和 velocity_config 去掉 config
> > @ye-luo-xi-tui @BruceLannn 发现了很多小问题。review 质量极低。reviewer 会不会太少？
> > 希望 review 能力能得到锻炼和进步，又快又准地读懂别人的代码+定位问题和缺陷也是一种重要的能力~
> 
> 确实is_need_reverse有点怪，本意是“是否需要翻转”，感觉可以改成whether_need_reverse。（作用和rm_hw里的gpio的direction有点区别）

首先不需要 whether！

另外你一直说翻转翻转根本就没能描述清楚你说的机制。你用 “翻转” 这个词我一开始是真的没有想明白是什么意思，第一次review也没看清楚。你知道在这个 “矿石翻转机构” 的程序用 “翻转” 这个词有多少含义吗？

按你的描述不就是 “保持方向不变" 嘛。你把意思转了又转绕了又绕： “是否保持方向不变” -> “是否改变方向” -> “是否翻转”。你不觉得除了你自己其他人都不能看得懂，并觉得你这个说法很奇怪吗：）特别是 “是否改变方向” -> “是否翻转” 简直是神来一笔。

2023-04-11 16:26 UTC, qiayuanliao commented on multi_dof_controller/src/multi_dof_controller.cpp
> +}
> 这个是为了让某些辅助的电机的旋转方向不随输入值改变。（例如目前工程 pitch翻转时候，下层的两个电机同向转动来翻动pitch，上层两个电机（辅助电机）持续往下让矿石吃到下面两个电机的摩擦力），这个感觉和rm_hw那个有区别，有时候一些自己觉得简单的就没想着参考代码了，以后会注意。

确实是不一样的，不过我上次评论指的是 rm_hw 电机的 direction。

2023-04-11 16:57 UTC, ljq-lv commented
> @ljq-lv 为什么你没有 review？

我和他有时候在604直接面对面review了（捂脸

2023-04-11 18:09 UTC, qiayuanliao commented
> > > > is_need_reverse_ 改为 direction_ 或 dir_ 。rm_hw 有类似的东西命名，为啥要自己编一个而且还很诡异 is_need ...
> > > > position_config 和 velocity_config 去掉 config
> > > > @ye-luo-xi-tui @BruceLannn 发现了很多小问题。review 质量极低。reviewer 会不会太少？
> > > > 希望 review 能力能得到锻炼和进步，又快又准地读懂别人的代码+定位问题和缺陷也是一种重要的能力~
> > > 
> > > 
> > > 确实is_need_reverse有点怪，本意是“是否需要翻转”，感觉可以改成whether_need_reverse。（作用和rm_hw里的gpio的direction有点区别）
> > 
> > 
> > 首先不需要 whether！
> > 另外你一直说翻转翻转根本就没能描述清楚你说的机制。你用 “翻转” 这个词我一开始是真的没有想明白是什么意思，第一次review也没看清楚。你知道在这个 “矿石翻转机构” 的程序用 “翻转” 这个词有多少含义吗？
> > 按你的描述不就是 “保持方向不变" 嘛。你把意思转了又转绕了又绕： “是否保持方向不变” -> “是否改变方向” -> “是否翻转”。你不觉得除了你自己其他人都不能看得懂，并觉得你这个说法很奇怪吗：）特别是 “是否改变方向” -> “是否翻转” 简直是神来一笔。
> 
> 确实绕，一直把reversal当作翻转（其实是反转），然后取参数名字的时候查反转是reverse，搞着搞着一样了，感觉改成
> 
> ```
> change_direction 或者fixed_direction
> ```
> 
> 会清楚点

fixed_direction 可以~

2023-04-13 04:04 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +}
似乎并未找到rm_hw中有关电机的direction的参数，有gpio的diction参数。

2023-04-13 04:05 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +}
> > 这个是为了让某些辅助的电机的旋转方向不随输入值改变。（例如目前工程 pitch翻转时候，下层的两个电机同向转动来翻动pitch，上层两个电机（辅助电机）持续往下让矿石吃到下面两个电机的摩擦力），这个感觉和rm_hw那个有区别，有时候一些自己觉得简单的就没想着参考代码了，以后会注意。
> 
> 确实是不一样的，不过我上次评论指的是 rm_hw 电机的 direction。



似乎并未找到rm_hw中有关电机的direction的参数，有gpio的diction参数。

2023-04-13 04:07 UTC, L-SY commented
之前的一些问题已经相应更改的就resolve咯。

2023-04-14 03:12 UTC, ljq-lv commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
枚举名字

2023-04-14 04:59 UTC, L-SY commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
这个统一一下把，看是用msgs里面的还是加名字（因为现在所有控制器都没有加，确定后一并改了）。 @ye-luo-xi-tui

2023-04-14 07:22 UTC, ye-luo-xi-tui commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
> 这个统一一下把，看是用msgs里面的还是加名字（因为现在所有控制器都没有加，确定后一并改了）。 @ye-luo-xi-tui

@qiayuanliao 我认为用msg里的比较好，但是不知道为什么前辈的代码都是代码里额外定义枚举量？

2023-04-14 12:54 UTC, qiayuanliao commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
> > 这个统一一下把，看是用msgs里面的还是加名字（因为现在所有控制器都没有加，确定后一并改了）。 @ye-luo-xi-tui
> 
> @qiayuanliao 我认为用msg里的比较好，但是不知道为什么前辈的代码都是代码里额外定义枚举量？

**msg 里面肯定是需要有这个定义的。**

有很多额外的定义是因为第一年半并不知道可以把枚举写成在 msg 这种形式。

不过额外再定义的话方便移植，但现在和ros绑定的还挺深的，所以意义也不大。

2023-04-14 13:07 UTC, ye-luo-xi-tui commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
> 

@L-SY 所以所有控制器统一用msg里的枚举？

2023-04-14 13:07 UTC, ye-luo-xi-tui commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
> > > 这个统一一下把，看是用msgs里面的还是加名字（因为现在所有控制器都没有加，确定后一并改了）。 @ye-luo-xi-tui
> > 
> > 
> > @qiayuanliao 我认为用msg里的比较好，但是不知道为什么前辈的代码都是代码里额外定义枚举量？
> 
> **msg 里面肯定是需要有这个定义的。**
> 
> 有很多额外的定义是因为第一年半并不知道可以把枚举写成在 msg 这种形式。
> 
> 不过额外再定义的话方便移植，但现在和ros绑定的还挺深的，所以意义也不大。

@L-SY 所以所有控制器统一用msg里的枚举？

2023-04-15 05:50 UTC, L-SY commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  enum
> > > > 这个统一一下把，看是用msgs里面的还是加名字（因为现在所有控制器都没有加，确定后一并改了）。 @ye-luo-xi-tui
> > > 
> > > 
> > > @qiayuanliao 我认为用msg里的比较好，但是不知道为什么前辈的代码都是代码里额外定义枚举量？
> > 
> > 
> > **msg 里面肯定是需要有这个定义的。**
> > 有很多额外的定义是因为第一年半并不知道可以把枚举写成在 msg 这种形式。
> > 不过额外再定义的话方便移植，但现在和ros绑定的还挺深的，所以意义也不大。
> 
> @L-SY 所以所有控制器统一用msg里的枚举？

OK已经改成rm_msgs::MultiDofCmd::VELOCITY这类的形式了，这样可以那我新开个Pr把其他的控制器都改了？

2023-04-17 12:12 UTC, L-SY commented
加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。

2023-04-17 16:46 UTC, ye-luo-xi-tui commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  judgeMotionGroup(cmd_multi_dof_);
成员变量明明能直接用为什么要传进去

2023-04-17 16:53 UTC, qiayuanliao commented
> 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。

又是一个很绕的名称 + 我不理解为什么需要这个

2023-04-18 02:25 UTC, L-SY commented
> > 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。
> 
> 又是一个很绕的名称 + 我不理解为什么需要这个

名称按照fix_direction的思路写的，calibrated是已经校准，然后它是一个bool值，1是已经校准，0是没有校准。

加入的原因：
- 原来的POSITION模式下是为了工程发动作组写的，类似于action（翻转没有校准所以只能在当前位置上加值），昨天在测试新的末端的时候想到可以直接用这个控制器和对应的commandsender来测试，只需要加一个校准就好了。
- 加这个参数就可以实现官方GroupPositionController的效果了。
- 感觉这个可以不只是用在翻转上，一些不需要太多状态切换的机构也可以使用。（像飞镖用了多个官方控制器，一定程度上可以用这个控制器代替）

2023-04-18 02:29 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  judgeMotionGroup(cmd_multi_dof_);
这个地方确实怪，是为了实现result计算那里可以直接丢进一个循环。
```
std::vector<std::string> motion_names = { "linear_x", "linear_y", "linear_z", "angular_x", "angular_y", "angular_z" };
  std::vector<double> motion_values = { msg.linear.x,  msg.linear.y,  msg.linear.z,
                                        msg.angular.x, msg.angular.y, msg.angular.z };
```
这个是为了实现类似map的效果，不用map的原因是map写出来较长而且result计算那里不如这个方便。

2023-04-18 02:30 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  judgeMotionGroup(cmd_multi_dof_);
> 成员变量明明能直接用为什么要传进去

确实不需要传，已改正。

2023-04-18 03:17 UTC, L-SY commented
> 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，结果值的计算不受position_per_step的影响，具体计算放在[https://github.com/rm-controls/rm_controllers/pull/122/files#diff-8a22615eacd2012c38cafe618fc76b33e0d3c85bbf6f82ead0ff0694398f00e5R140-R168。](https://github.com/rm-controls/rm_controllers/pull/122/files#diff-8a22615eacd2012c38cafe618fc76b33e0d3c85bbf6f82ead0ff0694398f00e5R140-R168%E3%80%82)

140-168行，（链接用法：像正常对某一段进行comment一样按绿色正方形选中，然后此时的页面的链接就指向了这几行，可以跨pr引用）

2023-04-18 04:54 UTC, ye-luo-xi-tui commented
> > > 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。
> > 
> > 
> > 又是一个很绕的名称 + 我不理解为什么需要这个
> 
> 名称按照fix_direction的思路写的，calibrated是已经校准，然后它是一个bool值，1是已经校准，0是没有校准。
> 
> 加入的原因：
> 
>     * 原来的POSITION模式下是为了工程发动作组写的，类似于action（翻转没有校准所以只能在当前位置上加值），昨天在测试新的末端的时候想到可以直接用这个控制器和对应的commandsender来测试，只需要加一个校准就好了。
> 
>     * 加这个参数就可以实现官方GroupPositionController的效果了。
> 
>     * 感觉这个可以不只是用在翻转上，一些不需要太多状态切换的机构也可以使用。（像飞镖用了多个官方控制器，一定程度上可以用这个控制器代替）

就当位置指令是增量不就好了，既没机械限位也没光电开关根本就做不到真正的校准。

第一个原因不知所云，看不出因果关系。
后面都是你在自说自话了，完全跟不上你的脑回路

**P.S:先能合并吧，再加新功能得到猴年马月才能合并了**

2023-04-18 13:29 UTC, L-SY commented
> > > > 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。
> > > 
> > > 
> > > 又是一个很绕的名称 + 我不理解为什么需要这个
> > 
> > 
> > 名称按照fix_direction的思路写的，calibrated是已经校准，然后它是一个bool值，1是已经校准，0是没有校准。
> > 加入的原因：
> > ```
> > * 原来的POSITION模式下是为了工程发动作组写的，类似于action（翻转没有校准所以只能在当前位置上加值），昨天在测试新的末端的时候想到可以直接用这个控制器和对应的commandsender来测试，只需要加一个校准就好了。
> > 
> > * 加这个参数就可以实现官方GroupPositionController的效果了。
> > 
> > * 感觉这个可以不只是用在翻转上，一些不需要太多状态切换的机构也可以使用。（像飞镖用了多个官方控制器，一定程度上可以用这个控制器代替）
> > ```
> 
> 就当位置指令是增量不就好了，既没机械限位也没光电开关根本就做不到真正的校准。
> 
> 第一个原因不知所云，看不出因果关系。 后面都是你在自说自话了，完全跟不上你的脑回路
> 
> **P.S:先能合并吧，再加新功能得到猴年马月才能合并了**

已经回退

2023-04-18 17:34 UTC, qiayuanliao commented
> > > 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。
> > 
> > 
> > 又是一个很绕的名称 + 我不理解为什么需要这个
> 
> 名称按照fix_direction的思路写的，calibrated是已经校准，然后它是一个bool值，1是已经校准，0是没有校准。
> 
> 加入的原因：
> 
> * 原来的POSITION模式下是为了工程发动作组写的，类似于action（翻转没有校准所以只能在当前位置上加值），昨天在测试新的末端的时候想到可以直接用这个控制器和对应的commandsender来测试，只需要加一个校准就好了。
> * 加这个参数就可以实现官方GroupPositionController的效果了。
> * 感觉这个可以不只是用在翻转上，一些不需要太多状态切换的机构也可以使用。（像飞镖用了多个官方控制器，一定程度上可以用这个控制器代替）

靠, 我看不懂，@ye-luo-xi-tui 能不能用通俗一点的话帮忙解释一下他想干啥

2023-04-19 05:34 UTC, L-SY commented
> > > > 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。
> > > 
> > > 
> > > 又是一个很绕的名称 + 我不理解为什么需要这个
> > 
> > 
> > 名称按照fix_direction的思路写的，calibrated是已经校准，然后它是一个bool值，1是已经校准，0是没有校准。
> > 加入的原因：
> > 
> > * 原来的POSITION模式下是为了工程发动作组写的，类似于action（翻转没有校准所以只能在当前位置上加值），昨天在测试新的末端的时候想到可以直接用这个控制器和对应的commandsender来测试，只需要加一个校准就好了。
> > * 加这个参数就可以实现官方GroupPositionController的效果了。
> > * 感觉这个可以不只是用在翻转上，一些不需要太多状态切换的机构也可以使用。（像飞镖用了多个官方控制器，一定程度上可以用这个控制器代替）
> 
> 靠, 我看不懂，@ye-luo-xi-tui 能不能用通俗一点的话帮忙解释一下他想干啥

本来想加强这个控制器的适用范围。已经回退到原来版本。

2023-04-25 05:57 UTC, L-SY commented
@ye-luo-xi-tui @qiayuanliao 请问还有什么地方需要改的？

2023-04-26 15:23 UTC, ye-luo-xi-tui commented
> > > > 加入了calibrated参数，应用在如果电机位置可以校准，然后需要绝对位置的情况下运动，接收值消息的值即为输出值。
> > > 
> > > 
> > > 又是一个很绕的名称 + 我不理解为什么需要这个
> > 
> > 
> > 名称按照fix_direction的思路写的，calibrated是已经校准，然后它是一个bool值，1是已经校准，0是没有校准。
> > 加入的原因：
> > 
> > * 原来的POSITION模式下是为了工程发动作组写的，类似于action（翻转没有校准所以只能在当前位置上加值），昨天在测试新的末端的时候想到可以直接用这个控制器和对应的commandsender来测试，只需要加一个校准就好了。
> > * 加这个参数就可以实现官方GroupPositionController的效果了。
> > * 感觉这个可以不只是用在翻转上，一些不需要太多状态切换的机构也可以使用。（像飞镖用了多个官方控制器，一定程度上可以用这个控制器代替）
> 
> 靠, 我看不懂，@ye-luo-xi-tui 能不能用通俗一点的话帮忙解释一下他想干啥

我也没看懂

2023-04-26 15:25 UTC, ye-luo-xi-tui commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  bool state_changed_{}, position_change_{ true }, calibrated_{};
回退没回干净，clion理应有warning

2023-04-26 15:26 UTC, ye-luo-xi-tui commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  judgeMotionGroup(cmd_multi_dof_);
还没改

2023-04-26 15:28 UTC, ye-luo-xi-tui commented
问问骏骐哥怎么合并commit吧，这commit数量太恐怖了

2023-05-07 09:00 UTC, L-SY commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  bool state_changed_{}, position_change_{ true }, calibrated_{};
已删除。

2023-05-07 09:03 UTC, L-SY commented on multi_dof_controller/src/multi_dof_controller.cpp
> +  judgeMotionGroup(cmd_multi_dof_);
已改

2023-05-07 13:51 UTC, ye-luo-xi-tui commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  hardware_interface::EffortJointInterface* effort_joint_interface_{};
局部变量

2023-05-07 13:52 UTC, ye-luo-xi-tui commented on multi_dof_controller/include/multi_dof_controller/multi_dof_controller.h
> +  effort_controllers::JointPositionController ctrl_yaw_, ctrl_pitch_;
从云台控制器复制过来的吧，clion真的没有warning吗？别用这种错误折磨reviewer了吧

2023-05-09 11:02 UTC, closed without merging