Add balance auto exit block.
rm-controls/rm_controllers pull request #123
Opened 2023-03-29 14:40 UTC by chenhuiYu00

针对场上平衡步兵可能在上电重启后在墙角卡住的情况，加入了自动退出卡住状态的代码。判断条件是轮子的扭矩大于一定值，轮子速度小于一定值且倾角大于一定值(针对倒下的情况)，以上情况在持续一段时间后进入卡住状态，车体会向后运动一小段距离以退出可能卡住的区域，之后再尝试重新起立。

相关参数：

2023-03-30 04:43 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/src/balance.cpp
> +      state_pub_.publish(state);
应该用实时发布器，当时是我的疏忽，顺便改一下吧

2023-03-30 04:46 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/src/balance.cpp
> +      }
学其他控制器封装成函数吧

2023-04-01 10:04 UTC, qiayuanliao requested changes
enum BalanceState 和 rm_msgs::BalanceState 不是一个东西吧？看了我老半天。
如果不是一个东西，必然不能同名呀，读的时候太混乱了

2023-04-01 11:27 UTC, chenhuiYu00 commented
> 

在起名上不太确定所以写成了BalanceState，目前平衡步兵的状态有正常运动的NORMAL和被卡住的BLOCK，在未来可能还有准备进入飞坡的状态。如果要改的话换成BalanceModel怎么样？

2023-04-01 11:28 UTC, chenhuiYu00 commented
> enum BalanceState 和 rm_msgs::BalanceState 不是一个东西吧？看了我老半天。 如果不是一个东西，必然不能同名呀，读的时候太混乱了

在起名上不太确定所以写成了BalanceState，目前平衡步兵的状态有正常运动的NORMAL和被卡住的BLOCK，在未来可能还有准备进入飞坡的状态。如果要改的话换成BalanceModel怎么样？

2023-04-01 15:17 UTC, ye-luo-xi-tui commented
> > enum BalanceState 和 rm_msgs::BalanceState 不是一个东西吧？看了我老半天。 如果不是一个东西，必然不能同名呀，读的时候太混乱了
> 
> 在起名上不太确定所以写成了BalanceState，目前平衡步兵的状态有正常运动的NORMAL和被卡住的BLOCK，在未来可能还有准备进入飞坡的状态。如果要改的话换成BalanceModel怎么样？

MotionState?

2023-04-02 16:08 UTC, qiayuanliao commented
> > enum BalanceState 和 rm_msgs::BalanceState 不是一个东西吧？看了我老半天。 如果不是一个东西，必然不能同名呀，读的时候太混乱了
> 
> 在起名上不太确定所以写成了BalanceState，目前平衡步兵的状态有正常运动的NORMAL和被卡住的BLOCK，在未来可能还有准备进入飞坡的状态。如果要改的话换成BalanceModel怎么样？

是 BalanceMode 吧哈哈哈哈，模式而不是模型。我觉得可以。

我review代码时是没有 clion 的，纯看文本，乱起名字或 codestyle 错我很容易困惑

2023-04-06 13:20 UTC, qiayuanliao approved these changes
不错！ 以后可以考虑把 拨弹和 这个的逻辑写在 common 里面，叫 BlockDetector 啥的。

2023-04-06 13:23 UTC, merged