Modify shooter controller to achieve function of adjusting friction wheel speed by key
rm-controls/rm_controllers pull request #137
Opened 2023-07-11 03:20 UTC by 1moule

1. 功能实现：mamual通过按键，通过service向控制器发出一个请求，内容是摩擦轮额外的转速，控制器拿到这个值后再对摩擦轮转速进行调整，从而实现按键调整摩擦轮转速的功能
2. 对控制器进行修改，增加ServiceServer以及对应回调等，实现上述功能

2023-07-11 03:43 UTC, ye-luo-xi-tui commented
干啥的呀，怎么都没人跟我提起过

2023-07-12 08:47 UTC, 1moule commented
> 干啥的呀，怎么都没人跟我提起过

按键调整摩擦轮转速，之前分区赛写的

2023-07-14 06:31 UTC, ye-luo-xi-tui commented
你看看让那个服务直接修改动态调参里的转速吧，少个变量。可以只修改当前命令的射速

2023-07-17 15:35 UTC, qiayuanliao commented
> 你看看让那个服务直接修改动态调参里的转速吧，少个变量。可以只修改当前命令的射速

这个的结果是？似乎用这个方法更好点？

2023-07-18 06:18 UTC, qiayuanliao commented
> > > 你看看让那个服务直接修改动态调参里的转速吧，少个变量。可以只修改当前命令的射速
> > 
> > 
> > 这个的结果是？似乎用这个方法更好点？
> 
> 这个要在服务的回调里加上当前命令射速的判断，感觉现在这个会简洁一点

但感觉搞一个“只有float”的srv也太诡异了，还不如把**转速值**直接放在 ShooterCmd 里面？ 

@ye-luo-xi-tui 你知道“*转速值**直接放在 ShooterCmd 里面” 是啥意思吧？你觉得这样会不会好点呢?

2023-07-19 07:14 UTC, ye-luo-xi-tui commented
> > > > 你看看让那个服务直接修改动态调参里的转速吧，少个变量。可以只修改当前命令的射速
> > > 
> > > 
> > > 这个的结果是？似乎用这个方法更好点？
> > 
> > 
> > 这个要在服务的回调里加上当前命令射速的判断，感觉现在这个会简洁一点
> 
> 但感觉搞一个“只有float”的srv也太诡异了，还不如把**转速值**直接放在 ShooterCmd 里面？
> 
> @ye-luo-xi-tui 你知道“*转速值**直接放在 ShooterCmd 里面” 是啥意思吧？你觉得这样会不会好点呢?

那直接把ShootCmd里的speed替换为具体的摩擦轮转速？

2023-07-22 17:01 UTC, qiayuanliao commented
> > > > > 你看看让那个服务直接修改动态调参里的转速吧，少个变量。可以只修改当前命令的射速
> > > > 
> > > > 
> > > > 这个的结果是？似乎用这个方法更好点？
> > > 
> > > 
> > > 这个要在服务的回调里加上当前命令射速的判断，感觉现在这个会简洁一点
> > 
> > 
> > 但感觉搞一个“只有float”的srv也太诡异了，还不如把**转速值**直接放在 ShooterCmd 里面？
> > @ye-luo-xi-tui 你知道“*转速值**直接放在 ShooterCmd 里面” 是啥意思吧？你觉得这样会不会好点呢?
> 
> 那直接把ShootCmd里的speed替换为具体的摩擦轮转速？

嗯，我就是这个意思，你想想会不会有什么问题？如果没有，可以这么做

2023-07-30 16:32 UTC, qiayuanliao requested changes
其他发射相关代码的 "qd" "rotate_speed" 等一切与摩擦轮转速相关的值的变量都统一改为 wheel_speed

这是历史遗留问题，不是你的问题，这次顺便改了。

改完之后叶子哥确定都改了，就直接merge，不需要再次 review 了~

2023-08-02 10:53 UTC, merged