New power limit
rm-controls/rm_controllers pull request #19
Opened 2021-10-30 17:56 UTC by ye-luo-xi-tui

2021-11-01 06:22 UTC, qiayuanliao requested changes
代码写得过于复杂，你需要理清思路。
另外重复操作过多，可以在第一个 for 中计算出 ` a, b, c, zoom_coeff`，判断 `zoom_coeff` 是否小于 1，若小于1即超过最大功率

2021-11-01 06:22 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +      !controller_nh.getParam("power/effort_coeff", effort_coeff_) || !controller_nh.getParam("timeout", timeout_))
把获取 timeout 放到紧跟着获取 publish_rate 后面

2021-11-01 06:22 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +  double total_power{ 0.0 };
` double total_power = 0.;`

2021-11-01 06:22 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
>      if (joint.getName().find("wheel") != std::string::npos)
把注释放在 `if` 同一行吧

2021-11-01 06:22 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
>    for (const auto& joint : joint_handles_)  // Loop all chassis joint
如果你需要 `i`，直接使用 `for(int i = 0; i < ; ++i)` 而不是 `for ( : ) `

2021-11-01 06:22 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +    double a{ 0.0 }, b{ 0.0 }, c{ 0.0 };
不要用大括号初始化

2021-11-01 06:22 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +  std::vector<double> real_vel;
似乎根本就不需要把这些存下来，你的代码过于复杂

2021-11-01 12:33 UTC, qiayuanliao requested changes
可以不需要 变量 `a b c` 吧？

2021-11-02 15:44 UTC, ye-luo-xi-tui commented
> 可以不需要 变量 `a b c` 吧？

愿闻其详

2021-11-02 15:48 UTC, qiayuanliao commented
> > 可以不需要 变量 `a b c` 吧？
> 
> 愿闻其详

当我没说

2021-11-02 15:53 UTC, qiayuanliao requested changes
合理简化，有变量是不需要的

2021-11-02 15:53 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +  }
可不使用分支if语句，直接用
```
joint.setCommand( zoom_coeff > 1.? 1. : joint.getCommand() * zoom_coeff )
```
你多搞个 `double cmd = joint.getCommand();` 干嘛？？？ cmd 只用了一次就直接用啊

2021-11-02 15:53 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +        double cmd = joint.getCommand();
你多搞个` double cmd = joint.getCommand();` 干嘛？？？ cmd 只用了一次就直接用啊

2021-11-02 15:53 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +  }
这个旧代码有，求你仔细阅读旧代码

2021-11-02 17:55 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/src/chassis_base.cpp
> +        double cmd = joint.getCommand();
之前是`joint.setCommand(joint.getCommand()*zoom_coeff)`，发现有时会疯车。这样写之后就没疯过了。

2021-11-02 18:03 UTC, qiayuanliao commented on rm_chassis_controllers/src/chassis_base.cpp
> +        double cmd = joint.getCommand();
不可能

2021-11-15 13:47 UTC, merged