Update rm_chassis_controllers README.
rm-controls/rm_controllers pull request #3
Opened 2021-08-21 16:31 UTC by cailiyawkl

2021-08-21 18:14 UTC, qiayuanliao requested changes
有非常多的错误 @BruceLannn  @Edwinlinks  你们先找一次

2021-08-24 18:22 UTC, BruceLannn requested changes
Overview看技术报告里面怎么写，然后学shooter硬件接口怎么写的，内容看技术报告，License里面加上链接（去看calibration的）

2021-08-25 07:54 UTC, qiayuanliao requested changes
格式和内容都还是有很多错误 @BruceLannn @Edwinlinks

2021-08-28 14:57 UTC, BruceLannn requested changes
关键词加上ROS、RoboMaster，Author那部分去看看gimbal或者calibration的格式，28行obtain改为get，35行删掉，122，124，，126，128的默认值删掉，coeff具体含义写清楚，min_vel的含义也是，这两个参数含义可以在英雄技术报告的功率限制里面看

2021-08-28 16:44 UTC, qiayuanliao requested changes

2021-08-28 16:44 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
> +acceleration commands, and the data is returned by the motor to calculate The speed and posture of the chassis are
@BruceLannn @kbxkgxjg  @Edwinlinks  此处有不少错误

2021-08-28 16:44 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
> +a [BSD 3-Clause license](http://192.168.0.100:7070/dynamicx/rm_chassis_controllers/-/blob/master/LICENSE).
网址有问题

2021-08-28 16:44 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
> +and 20.04. This is research code, expect that it changes often and any fitness for a particular purpose is disclaimed.
不需要换行吧？

2021-08-28 16:44 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
> +`RoboSateInterface` It is used for high-frequency maintenance of the transformation relationship of changing odom to
这里为什么就是It is used 上面就是 Used to

2021-08-28 16:44 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
> +the [Issue Tracker](https://github.com/gdut-dynamic-x/simple_chassis_controller/issues) .
simple_chassis_controller？ 你穿越了？

2021-08-29 05:43 UTC, qiayuanliao requested changes

2021-08-29 05:43 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
>    Angle of distortion.
>  Angle of distortion. 


是啥意思？

2021-08-29 05:43 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
> +  It is safety factor.The influence of power loss can be conservatively reduced by adjusting it.
> It is safety 

为什么这里的表述就突然有了 "It is"?  而其他所有参数都没有？你不觉得很违和吗

2021-08-29 05:43 UTC, qiayuanliao commented on rm_chassis_controllers/README.md
>    Allowed period (in s) between two commands. If the time is exceed this period, it will turn off.
turn off 什么东西？怎么turn off的？ 这个默认值是有意义的

2021-08-29 14:30 UTC, kbxkgxjg commented
写作者那参考一下calibration里面的，hardware不同接口之间应该是没有空格的，topics里面 的解释应该换行，不同topic之间也要空行，参数那里也是。还有既然你都是在参数里面，你common和balace里也有很明显的格式不统一，加粗注意一下

2021-08-29 15:17 UTC, kbxkgxjg commented
wheel_base 有点没看懂 轴心之间的距离，是轮子前后轴还是左右还是什么。。。twist_angular，感觉解释有点还是没懂，翻译就是扭曲v的角度，你可以类似“以Z轴为中心，旋转偏离x轴的角度”？，这样详细一点的解释。。。min_vel那里minimum speed直接用min_vel可能会更好？还有解释下是线速度还是角速度，可以放在最开头先解释。。。。timeout后面的那个it指的是什么 停止。。。‘a’ 'b'那里是不是有点简单，还是他就是单纯的这个意思，还有‘q’‘r’也不是很清楚。。。

2021-08-29 15:24 UTC, kbxkgxjg commented
那个position解释 不清楚，我第一眼看到以为是轮子基于base link坐标系下的位置。。。实际上应该指的是类似与电机转动的角度这样，应该解释更清楚一些

2021-08-29 16:05 UTC, qiayuanliao commented
> 那个position解释 不清楚，我第一眼看到以为是轮子基于base link坐标系下的位置。。。实际上应该指的是类似与电机转动的角度这样，应该解释更清楚一些

哪个position？ 对着代码说

2021-08-29 16:07 UTC, kbxkgxjg commented
最后对舵轮 Swerve里 对position的解释 都是The position of right front wheel.，这样的解释和没有似的

2021-08-29 16:09 UTC, qiayuanliao commented
> wheel_base 有点没看懂 轴心之间的距离，是轮子前后轴还是左右还是什么。。。twist_angular，感觉解释有点还是没懂，翻译就是扭曲v的角度，你可以类似“以Z轴为中心，旋转偏离x轴的角度”？，这样详细一点的解释。。。min_vel那里minimum speed直接用min_vel可能会更好？还有解释下是线速度还是角速度，可以放在最开头先解释。。。。timeout后面的那个it指的是什么 停止。。。‘a’ 'b'那里是不是有点简单，还是他就是单纯的这个意思，还有‘q’‘r’也不是很清楚。。。

wheel_base 的定义在代码里面有。
“twist_angular” 应该改名为 “twist_angle” （新开一个pull request 改）。
“以Z轴为中心，旋转偏离x轴的角度” 依旧是废话，看过代码都知道这是“扭腰”这个模式（状态）下的扭动幅度。
一切东西都要按照代码来解释而不是在这里凭空编造扩写。

2021-08-29 16:09 UTC, qiayuanliao commented
> 写作者那参考一下calibration里面的，hardware不同接口之间应该是没有空格的，topics里面 的解释应该换行，不同topic之间也要空行，参数那里也是。还有既然你都是在参数里面，你common和balace里也有很明显的格式不统一，加粗注意一下

对着代码说，你看我是怎么评论calibration的

2021-08-29 16:13 UTC, kbxkgxjg commented
哦哦这些readme里的内容是辅助我们看代码理解的嘛，我对着看的时候没有看源代码

2021-08-30 14:30 UTC, kbxkgxjg commented
param那里的参数格式还是不对

2021-09-06 15:33 UTC, closed without merging