Add feedforward in gimbal control
rm-controls/rm_controllers pull request #37
Opened 2021-12-23 14:05 UTC by ye-luo-xi-tui

从urdf读质心位置和质量在仿真会出问题，而且感觉不太优雅，最后还是采取了从配置文件读参数的方法。

加前馈前
![加前馈前](https://ftp.bmp.ovh/imgs/2021/12/0f6aa1058c184002.gif)
平地加前馈后
![](https://ftp.bmp.ovh/imgs/2021/12/214dd9551ffdd41b.gif)
底盘倾斜，yaw转动，加前馈后
![](https://ftp.bmp.ovh/imgs/2021/12/95653165f3514d99.gif)

2021-12-26 15:41 UTC, qiayuanliao commented
ci 没过，而且urdf比配置文件优雅，你需要搞清楚为啥urdf会出问题

2021-12-26 16:07 UTC, ye-luo-xi-tui commented
> ci 没过，而且urdf比配置文件优雅，你需要搞清楚为啥urdf会出问题

因为我从urdf读质心位置和质量都只读pitch，而仿真中pitch以上的link都有自己的质心和质量。在测试中我很难排除imu质量的干扰。难道要遍历pitch及以上的link，求出整体的质心位置吗？

ci没过我看了，是找不到tf_eigen这个头文件，我认为应该让运维修。

2021-12-26 18:21 UTC, qiayuanliao commented
>  
> 因为我从urdf读质心位置和质量都只读pitch，而仿真中pitch以上的link都有自己的质心和质量。在测试中我很难排除imu质量的干扰。难道要遍历pitch及以上的link，求出整体的质心位置吗？

我上次明确而清晰地跟你讲过：“直接用urdf里面pitch的质量，以后让机械出urdf时把摄像头和其他所有东西的质量全都算在pitch_link里面”，而且你表示了赞同，现在又来给我反问什么遍历不遍历，你记不住你就录音，看得我血压大。
还有imu的质量本来就是乱给的。。。

> ci没过我看了，是找不到tf_eigen这个头文件，我认为应该让运维修。

等着我让运维修吗？？？你过不了为什么不是自己修或者找人修？？

2021-12-26 18:33 UTC, qiayuanliao requested changes

2022-01-15 13:10 UTC, qiayuanliao commented
CI 没过

2022-02-11 14:16 UTC, qiayuanliao commented
请解决合并冲突

2022-03-22 16:48 UTC, ye-luo-xi-tui commented
这里ci没过依然是因为rm_description。

2022-03-24 16:12 UTC, merged