Update tof_sensor_controller
rm-controls/rm_controllers pull request #39
Opened 2022-01-18 18:38 UTC by Edwinlinks

2022-01-18 20:52 UTC, ye-luo-xi-tui commented
没问题

2022-01-21 13:46 UTC, qiayuanliao requested changes
到底是 `tof_sensor_controller` 还是 `tof_sensor_controllers` ？

2022-03-10 17:40 UTC, Edwinlinks commented
经过思考我认为是tof_sensor_controller，并且修改

2022-03-11 02:00 UTC, qiayuanliao requested changes
你的pr标题只提到tof_senser_controller，实际上却改了一堆哨兵底盘控制器，理应分开两个pr好点

2022-03-11 14:13 UTC, closed without merging