Update rm_shooter_controller README
rm-controls/rm_controllers pull request #4
Opened 2021-08-21 18:52 UTC by Edwinlinks

2021-08-23 10:01 UTC, BruceLannn requested changes
安装包的命令行错了，launch文件的名字错了，确认一下anti_block_angle的单位是rad/s,还是rad

2021-08-23 10:03 UTC, BruceLannn requested changes
launch文件文件名错了，确认anti_block_angle的单位

2021-08-23 12:24 UTC, qiayuanliao requested changes
看技术报告再修改

2021-08-23 14:51 UTC, qiayuanliao requested changes
硬件接口！！！！！！！！！！

2021-08-23 14:56 UTC, qiayuanliao commented
> 硬件接口！！！！！！！！！！

我无法理解你的眼睛是有多瞎才看不到的

2021-08-24 18:16 UTC, BruceLannn requested changes
去看看ros_best_pratice还有calibratio里面的格式，一句一句对照

2021-08-25 11:56 UTC, BruceLannn requested changes
25行删掉不要，controller configuration那里留下一个完整的例子

2021-08-28 11:02 UTC, Edwinlinks commented on rm_shooter_controllers/README.md
> +**Keywords:** shooter, jam detection, ROS
现在我将关键词改为了shooter, ROS, robomaster这样子可以吗

2021-08-28 11:41 UTC, Edwinlinks commented on rm_shooter_controllers/README.md
格式错误是指**command**后面要接一个空格吗，这个格式问题已修改

2021-08-28 15:19 UTC, Edwinlinks commented on rm_shooter_controllers/README.md
> +**Keywords:** shooter, jam detection, ROS
已重新修改

2021-08-29 06:46 UTC, kbxkgxjg commented
License的链接好像少了 hardware interface 的标点有错误， ROSAPI里的数据类型 对一下calibration看 有错误，还有标点符号也有错误。注意句号的使用

2021-08-29 07:05 UTC, kbxkgxjg commented
关于拨弹电机卡住参数的解释里面，第一个and后面直接说角速度可能有点少了对象？ 对于overtime的解释里面，也没说清楚是什么电机，it指代的没说清楚是什么的状态变了，后面几个也是。。每个参数应该都要有清晰的主语，你就模拟一下，假如读者读完第一个后就忘了那个，然后看后面的参数解释，他不知道这些的对象都是bo弹电机，还有转换状态最好用switch from to 组合 switch to这样

2021-08-29 14:50 UTC, kbxkgxjg commented
the state of shooter controller 可以改成 shooter controller state这样就说射击控制器进入了BLOCK状态，然后状态这些表示 用全英文大写比较好。overtime那里能不能这么表示“如果射击控制器进入了BLOCK状态并且持续超过了‘’，射击控制器进入其他状态”就不用解释 则是超时了，你看看calibration里 threshold 的解释，看看能不能参考一下

2021-08-29 14:56 UTC, kbxkgxjg commented
anti_block_angle的解释里面可以分成两个句子吧，不然有点难读。。。一个是BLOCK的时候，进行反转。然后才When，就,改成.  不然怪怪的。。。然后前面的装换状态最好加个主语吧，不然可能理解成是摩擦轮的状态

2021-08-30 17:53 UTC, closed without merging