Delete some config files in rm_controllers.
rm-controls/rm_controllers pull request #45
Opened 2022-03-25 09:27 UTC by mlione

2022-03-26 03:25 UTC, mlione commented
已经对yaml文件进行了重命名。

2022-03-26 03:38 UTC, mlione commented
有些文件夹仍存在两个yaml一个是模板一个是某个兵种的或者仍有不同兵种的yaml文件的原因是我认为它们之间的yaml文件内容有较大区别。

2022-03-26 03:39 UTC, qiayuanliao commented
合并有冲突

2022-03-26 03:39 UTC, qiayuanliao commented
@ye-luo-xi-tui

2022-03-26 03:44 UTC, ye-luo-xi-tui commented
> 有些文件夹仍存在两个yaml一个是模板一个是某个兵种的或者仍有不同兵种的yaml文件的原因是我认为它们之间的yaml文件内容有较大区别。

举例

2022-03-26 03:48 UTC, mlione commented
> 

rm_chassis_controllers 下的各个yaml文件之间有较大区别
rm_gimbal_controllers 下的sentry.yaml和其他的yaml文件有较大区别

2022-03-26 03:55 UTC, ye-luo-xi-tui commented
> > 
> 
> rm_chassis_controllers 下的各个yaml文件之间有较大区别 rm_gimbal_controllers 下的sentry.yaml和其他的yaml文件有较大区别

chassis_controller目前有三种类型，分别是麦轮，舵轮，全向轮。你可以每种轮系留一个模板文件。（目前standard3是全向轮，standard4是舵轮，standard5是麦轮）

2022-03-26 03:56 UTC, ye-luo-xi-tui commented
> > > 
> > 
> > 
> > rm_chassis_controllers 下的各个yaml文件之间有较大区别 rm_gimbal_controllers 下的sentry.yaml和其他的yaml文件有较大区别
> 
> chassis_controller目前有三种类型，分别是麦轮，舵轮，全向轮。你可以每种轮系留一个模板文件。（目前standard3是全向轮，standard4是舵轮，standard5是麦轮）

然后chassis_controller的launch文件可跟着做一定修改，可设置一个参数决定要加载的轮系配置文件。

2022-03-26 04:25 UTC, ye-luo-xi-tui commented
> > 
> 
> rm_chassis_controllers 下的各个yaml文件之间有较大区别 rm_gimbal_controllers 下的sentry.yaml和其他的yaml文件有较大区别

哨兵的云台配置文件和其他的是一样的，只是可能太久没更新，出现了一些已经被删掉的参数。

2022-03-26 04:26 UTC, ye-luo-xi-tui commented
另外请解决合并冲突

2022-03-28 03:54 UTC, ye-luo-xi-tui commented
文件名全小写

2022-03-28 07:16 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/launch/load_controllers.launch
> +    <arg name="chassis_type" default="$(env CHASSIS_TYPE)" doc="Chassis type [Omni, Swerve, Mecanum]"/>
搞成一个普通的参数就好了，没必要弄成环境变量了。

2022-03-28 07:17 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/launch/load_controllers.launch
> +    <rosparam file="$(find rm_chassis_controllers)/config/$(arg chassis_type).yaml" command="load"/>
你这里也对不上配置文件啊

2022-03-29 19:18 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/launch/load_controllers.launch
> +    <arg name="chassis_type" default="false"/>
emm，你default还是设成麦轮吧。false怪怪的。

2022-03-30 04:45 UTC, qiayuanliao commented on rm_chassis_controllers/launch/load_controllers.launch
> +    <arg name="chassis_type" default="false"/>
+1

2022-03-30 04:45 UTC, qiayuanliao requested changes
搞成一个commit吧 太多了

2022-04-01 16:21 UTC, qiayuanliao commented
@ye-luo-xi-tui 再确认一次

2022-04-01 17:25 UTC, ye-luo-xi-tui commented
> @ye-luo-xi-tui 再确认一次

我觉得没问题

2022-04-02 01:09 UTC, merged