Complete tof sensor controller
rm-controls/rm_controllers pull request #47
Opened 2022-03-29 16:41 UTC by Edwinlinks

2022-03-30 00:12 UTC, qiayuanliao requested changes

2022-03-30 00:12 UTC, qiayuanliao commented on tof_sensor_controller/package.xml
> +  <version>0.0.0</version>
版本号不对

2022-03-30 00:12 UTC, qiayuanliao commented on tof_sensor_controller/launch/load_controller.launch
> +    <node name="controller_spawner" pkg="controller_manager" type="controller_manager" output="screen"
似乎没必要这么写，只需要

2022-03-30 08:49 UTC, Edwinlinks commented on tof_sensor_controller/package.xml
> +  <version>0.0.0</version>
已修改版本号

2022-03-30 08:50 UTC, Edwinlinks commented on tof_sensor_controller/launch/load_controller.launch
> +    <node name="controller_spawner" pkg="controller_manager" type="controller_manager" output="screen"
修改为只加载sentry.yaml

2022-03-30 11:39 UTC, qiayuanliao approved these changes

2022-03-30 11:39 UTC, qiayuanliao commented
@ye-luo-xi-tui 看看

2022-04-03 05:12 UTC, qiayuanliao requested changes
参考 imu_sensor_controller， 一个机器人多个tof传感器时只需要一个tof_controller

2022-04-03 07:48 UTC, Edwinlinks commented
好的，我改一下

2022-04-04 06:21 UTC, Edwinlinks commented
已经按照要求修改为只加载一个控制器，并且已测试过是否正常收发。

2022-04-04 11:07 UTC, merged