Complete sentry catapult
rm-controls/rm_controllers pull request #49
Opened 2022-03-29 17:21 UTC by Edwinlinks

2022-03-30 00:04 UTC, qiayuanliao commented
@ye-luo-xi-tui 看一下，注意代码是否简洁

2022-04-02 01:10 UTC, qiayuanliao commented
@Edwinlinks

2022-04-02 16:22 UTC, Edwinlinks commented on rm_chassis_controllers/src/sentry.cpp
> +    ChassisBase::update(time, period);
这部分为多余代码，经测试后已删除

2022-04-03 05:11 UTC, qiayuanliao requested changes
配置文件应该放在 rm_config 了吧？

2022-04-03 07:42 UTC, Edwinlinks commented
是的

2022-04-06 01:44 UTC, qiayuanliao commented
> 是的

是你个头啊 我让你改啊，为什么还会有sentry的配置文件在这个仓库？？？

2022-04-06 09:42 UTC, Edwinlinks commented
我上次pr的时候注意到了这个但是我以为我已经修改了没仔细看，我在晚上下课后会重新修改

2022-04-06 10:01 UTC, qiayuanliao commented
还有合并冲突

2022-04-06 17:07 UTC, closed without merging