Make rm_orientation_controller publish tf use imu data on the topic
rm-controls/rm_controllers pull request #50
Opened 2022-03-29 19:16 UTC by ye-luo-xi-tui

2022-03-30 00:07 UTC, qiayuanliao requested changes

2022-03-30 00:07 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>    double publish_rate_{};
这个不需要了吧？

2022-03-30 01:41 UTC, ye-luo-xi-tui commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>    double publish_rate_{};
哪个

2022-03-30 04:27 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>    double publish_rate_{};
publish_rate_

2022-03-30 04:42 UTC, qiayuanliao requested changes

2022-03-30 04:42 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>    double publish_rate_{};
还有 last_br_

2022-03-30 04:42 UTC, qiayuanliao commented on rm_orientation_controller/src/orientation_controller.cpp
>    last_orientation_y = imu_sensor_.getOrientation()[1];
这段逻辑可能可以删掉了，每次都update就行

2022-03-30 04:42 UTC, qiayuanliao commented on rm_orientation_controller/src/orientation_controller.cpp
>    last_orientation_y = imu_sensor_.getOrientation()[1];
```
  if (imu_sensor_.getOrientation()[0] == last_orientation_x && imu_sensor_.getOrientation()[1] == last_orientation_y)
  {
    return;
  }
```
及其相关变量

2022-03-30 04:42 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
> -  std::shared_ptr<realtime_tools::RealtimePublisher<sensor_msgs::Imu> > imu_pub_;
对应的两个头文件没有删除

2022-03-30 04:42 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
> +  ros::Subscriber imu_data_sub_;
应该放在 原来 publisher的位置比较合适

2022-03-30 04:42 UTC, qiayuanliao commented on rm_orientation_controller/src/orientation_controller.cpp
> +    }
为什么还要按频率发送啊....... 肯定是每次触发都要发啊，你在想什么？？？？？ 服了

2022-03-31 17:12 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>  #include <sensor_msgs/Imu.h>
没有用到！！！

2022-03-31 17:12 UTC, qiayuanliao commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>  #include <sensor_msgs/Imu.h>
如果cpp用了 h 没用到就放到 cpp！我上次review已经告诉你要删掉两个头文件了，你。。。

2022-04-01 00:11 UTC, ye-luo-xi-tui commented on rm_orientation_controller/include/rm_orientation_controller/orientation_controller.h
>  #include <sensor_msgs/Imu.h>
> 如果cpp用了 h 没用到就放到 cpp！我上次review已经告诉你要删掉两个头文件了，你。。。

头文件的回调函数声明需要用到sensor_msgs/Imu

2022-04-01 10:45 UTC, merged