Update ReactionWheelController
rm-controls/rm_controllers pull request #57
Opened 2022-04-27 08:03 UTC by NaHCO3bc

Change the number of joint name reads,change the QR matrix to an array and update the rm_chassis_controllers_plugins.xml.

2022-04-27 08:08 UTC, NaHCO3bc commented
按照昨天布置的新任务对代码和参数文件进行了修改，上传了更新后的rm_chassis_controllers_plugins.xml

2022-04-27 08:16 UTC, qiayuanliao requested changes
不加思考地改.... 错漏百出，

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> +  ROS_ASSERT(joint.getType() == XmlRpc::XmlRpcValue::TypeString);
写得有点繁琐，参考 其他参数的获取方式即可，没必要判断类型了

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> +  wheel_rate /= num_joint;
？？？为什么还有joint的数量？？？你醒醒可以吗

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> +  joint_handles_.push_back(effort_joint_interface->getHandle(joint));
还要vector干嘛？

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> +        q_(i, i) = static_cast<int>(q[i][j]);
测试过吗？ 还有 R 怎么没有改？

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> +  u = k_ * (-x) / num_joint;  // regulate to zero: K*(0 - x)
？？？？

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
>      {
没看懂你这写的啥？？？？？

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
> +    q: [ [ 1.5 ],[ 10 ],[ 0.01 ] ]
为什么是这样写的？ 你这是 array吗？ 你这是 array 里面又套了array？

2022-04-27 08:16 UTC, qiayuanliao commented on rm_chassis_controllers/rm_chassis_controllers_plugins.xml
> +            EffortJointInterface type of hardware interface.
没写对，自己看哪里写错了

2022-04-28 08:53 UTC, NaHCO3bc commented
@ye-luo-xi-tui 来看看

2022-04-28 09:03 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-04-28 09:04 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
>    imus:
服了，说了好多次还是错。看清楚命名空间好吗

2022-04-28 09:10 UTC, NaHCO3bc commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
>    imus:
我翘我记得我已经改了

2022-04-28 09:12 UTC, NaHCO3bc commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
>    imus:
> 服了，说了好多次还是错。看清楚命名空间好吗

晕我明明记得已经改了

2022-04-28 09:18 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
>    imus:
> > 服了，说了好多次还是错。看清楚命名空间好吗
> 
> 晕我明明记得已经改了

。。代码里面哪里出现过imus。。你是当真不了解获取参数的机制是吗

2022-04-28 09:24 UTC, NaHCO3bc commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
>    imus:
> > > 服了，说了好多次还是错。看清楚命名空间好吗
> > 
> > 
> > 晕我明明记得已经改了
> 
> 。。代码里面哪里出现过imus。。你是当真不了解获取参数的机制是吗

我的我的，我现在先在github上改了，晚上去实验室再reset然后push

2022-04-28 11:27 UTC, NaHCO3bc commented
@ye-luo-xi-tui ok了

2022-04-28 11:33 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-04-28 11:57 UTC, qiayuanliao approved these changes

2022-04-28 11:57 UTC, qiayuanliao commented on rm_chassis_controllers/config/template_reaction_wheel.yaml
> +    joint: "reaction_wheel_joint"
要叫 `imu_name` 和 `joint_name` 还是 `imu` 和 `joint `？
你别同时用两种风格呀..

2022-04-28 11:57 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> -    ROS_ASSERT(q[i].size() == STATE_DIM);
我说得快爆血管的大小确认呢 ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

2022-04-28 11:57 UTC, qiayuanliao commented on rm_chassis_controllers/src/reaction_wheel.cpp
> -    ROS_ASSERT(r[i].size() == CONTROL_DIM);
我说得快爆血管的大小确认呢 ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

2022-04-28 12:03 UTC, qiayuanliao approved these changes

2022-04-28 12:03 UTC, merged