Add README.md about robot_state_controller.
rm-controls/rm_controllers pull request #59
Opened 2022-05-16 04:55 UTC by NaHCO3bc

2022-05-20 03:09 UTC, qiayuanliao commented
@NaHCO3bc 参考 [robot_state_publisher](http://wiki.ros.org/robot_state_publisher) 改善
@ye-luo-xi-tui 看看

2022-05-20 13:16 UTC, ye-luo-xi-tui requested changes

2022-05-20 13:16 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +  Get real-time transformation information.
感觉说了等于没说。。

2022-05-20 13:16 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +  Get static transformation information.
同上

2022-05-20 13:16 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +  Set publish frequency.
发布什么东西的频率

2022-05-20 13:16 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +  The Model given the name of parameter on parameter server using provided nodehandle.
这。。你自己知道自己在说啥吗

2022-05-20 13:16 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +  The Model given the name of parameter on parameter server using provided nodehandle.
全部改成“名词 + 修饰语”的结构。

2022-05-20 13:16 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +    publish_rate: 100
robot_state_controller 不需要读取/joint_state，所以其实并不需要joint_state_controller。而且你缩进还错了

2022-05-20 13:31 UTC, NaHCO3bc commented
> 义眼丁真，鉴定为重写

收到收到

2022-05-21 00:23 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +
名词+修饰语！参考底盘控制器

2022-07-20 06:56 UTC, ye-luo-xi-tui approved these changes

2022-07-20 07:07 UTC, ye-luo-xi-tui requested changes

2022-07-20 07:07 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> +Robot_state_controller uses the URDF specified by the parameter robot_description and the joint positions from the topic joint_states to calculate the forward kinematics of the robot and publish the
虽然已经过了很久了但还是改一下吧。
第一行"The robot_state_controller",
并不是"from the topic joint_states"，它是通过'joint_state_interface'获取关节位置的。
你这短短一句话不止一个语法错误，实在无力吐槽。

2022-07-20 07:07 UTC, ye-luo-xi-tui commented on robot_state_controller/README.md
> ++ `RobotStateInterface` Used to get tf buffer data of different robot states.
并没有看懂这句在说什么

2022-07-20 14:19 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-07-20 17:23 UTC, ye-luo-xi-tui approved these changes

2022-07-21 02:59 UTC, qiayuanliao commented
@ye-luo-xi-tui 

- 每个控制器可能不需要单独的 launch 文件了？
- 每个控制器只要把依赖和参数都讲清楚，不需要再单独讲怎么编译和怎么运行？

2022-07-21 08:25 UTC, ye-luo-xi-tui commented
> @ye-luo-xi-tui
> 
>     * 其实每个控制器可能不需要单独的 launch 文件了？
> 
>     * 每个控制器应该只要把依赖和参数都讲清楚，不需要再单独讲怎么编译和怎么运行？
> 
> 
> 你觉得呢？

- 或许可以搞成test文件夹
- 确实可以删掉

2022-07-23 02:03 UTC, ye-luo-xi-tui commented
> > @ye-luo-xi-tui
> > ```
> > * 其实每个控制器可能不需要单独的 launch 文件了？
> > 
> > * 每个控制器应该只要把依赖和参数都讲清楚，不需要再单独讲怎么编译和怎么运行？
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你觉得呢？
> 
>     * 或许可以搞成test文件夹
> 
>     * 确实可以删掉

@qiayuanliao

2022-07-26 16:02 UTC, qiayuanliao commented
> > > @ye-luo-xi-tui
> > > ```
> > > * 其实每个控制器可能不需要单独的 launch 文件了？
> > > 
> > > * 每个控制器应该只要把依赖和参数都讲清楚，不需要再单独讲怎么编译和怎么运行？
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 你觉得呢？
> > 
> > 
> > ```
> > * 或许可以搞成test文件夹
> > 
> > * 确实可以删掉
> > ```
> 
> @qiayuanliao

- test 文件夹好
- 让他删吧

2022-07-28 13:32 UTC, closed without merging