Add gpio_controller.
rm-controls/rm_controllers pull request #65
Opened 2022-05-20 03:29 UTC by XYM-github

Add gpio_controller.

2022-05-20 03:37 UTC, XYM-github commented
好像pre commit没过 我改一下

2022-05-22 16:23 UTC, qiayuanliao requested changes

2022-05-22 16:23 UTC, qiayuanliao commented on gpio_controller/config/gpio_controller.yaml
> +        type: "out"
我不理解为什么会在控制器里面定义GPIO是输出还是输入，这不应该是在rm_hw的配置文件确定的吗？
@ye-luo-xi-tui @XYM-github

2022-05-22 16:26 UTC, ye-luo-xi-tui commented on gpio_controller/config/gpio_controller.yaml
> +        type: "out"
控制器也需要知道gpio是输入还是输出，不然会有问题（通过interface传递这一信息?）

2022-05-22 16:27 UTC, qiayuanliao commented on gpio_controller/config/gpio_controller.yaml
> +        type: "out"
> 通过interface传递这一信息?

很明显是的...

2022-05-22 16:30 UTC, qiayuanliao commented on gpio_controller/config/gpio_controller.yaml
> +        type: "out"
其实 “输入和输出的handle（interface）不应该一样” ？

2022-05-22 16:31 UTC, XYM-github commented
好的，我改一改



---Original---
From: ***@***.***&gt;
Date: Mon, May 23, 2022 00:28 AM
To: ***@***.***&gt;;
Cc: "Yuexin ***@***.******@***.***&gt;;
Subject: Re: [rm-controls/rm_controllers] Add gpio_controller. (PR #65)




 
@qiayuanliao commented on this pull request.
 
 
In gpio_controller/config/gpio_controller.yaml:
 &gt; +      valve_1: +        type: "out"   
通过interface传递这一信息?
  
很明显是的...
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-05-22 16:31 UTC, ye-luo-xi-tui commented on gpio_controller/config/gpio_controller.yaml
> +        type: "out"
> > 通过interface传递这一信息?
> 
> 很明显是的...

其实也不用，有两个interface，哪个interface找到了对应的handle就是哪个

2022-05-22 16:34 UTC, qiayuanliao commented on gpio_controller/config/gpio_controller.yaml
> +        type: "out"
参考joint_state？和joint_command？
有个 gpio_state_controller是发所有gpio状态（无论是输入还是输出的），一般只运行一个。

有个 gpio_command_controller ？

我觉得你们需要更细致地讨论。有点绕

2022-05-22 17:01 UTC, qiayuanliao commented
就该有 gpio_state_handle和 gpio_command_handle

- 所有gpio都有state_handle
- 只有设置为输出的有 command_handle
-  state_handle 不要 claim（可以被多个控制器同时使用）
- command_handle需要claimed （只能被一个控制器同时使用，具体看handle和interface的class声明）


- state控制器和joint_state_controller一样，一次性把所有状态和名字发出来
- command 控制器和 effort_joint_controller一样（不过可以传 多个 handle 名）

2022-05-30 01:48 UTC, closed without merging