Add return position and center calibrate on calibration controller
rm-controls/rm_controllers pull request #68
Opened 2022-06-01 13:19 UTC by ljq-lv

2022-06-01 13:49 UTC, qiayuanliao requested changes
配置文件删掉，没用

2022-06-01 13:49 UTC, qiayuanliao commented on rm_calibration_controllers/include/rm_calibration_controllers/joint_calibration_controller.h
> +  double vel_search_{}, vel_threshold_{}, pos_threshold_{}, target_position_{};
统一命名格式和变量顺序

2022-06-01 13:49 UTC, qiayuanliao commented on rm_calibration_controllers/include/rm_calibration_controllers/joint_calibration_controller.h
> +  double vel_search_{}, vel_threshold_{}, pos_threshold_{}, target_position_{};
- 你到底要叫 vel 和 pos 还是 velocity 和 position，search/target 放在前面还是后面？

- 变量顺序为什么不和原来的一样？ 你看着不难受吗？xxx_threshold  到底要放在 第 1/3  个还是 第 2/4个？为什么你放在 第 2/3 个？

2022-06-01 13:49 UTC, qiayuanliao commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +    velocity_ctrl_.update(time, period);
狗屎，为什么会在这里另起一个if，所有时期都应该在上面的 switch case 里面完成啊。。。。

2022-06-02 11:31 UTC, qiayuanliao commented
@ye-luo-xi-tui 有一个问题，你找出来或者梯度找出来

2022-06-03 11:52 UTC, qiayuanliao commented
@ye-luo-xi-tui 有一个问题，你找出来或者梯度找出来

2022-06-04 12:26 UTC, qiayuanliao commented
@ljq-lv 还是有问题

2022-06-06 14:38 UTC, qiayuanliao commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +      halted |= actuator_.getHalted();
认真看行不行啊

2022-06-06 16:00 UTC, ye-luo-xi-tui commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +      velocity_ctrl_.update(time, period);
如果存在设置了return，校准完成后在切换控制器之前该关节保持在某个位置的需求，可以加一个if来判断选择速度控制器还是位置控制器。如果没有这个需求当我没说。

2022-06-06 16:11 UTC, ye-luo-xi-tui commented on rm_calibration_controllers/README.md
> +  When requesting to this server, it will return respond about whether target joints has been calibrated.
ros官方用的好像是response吧，还有joint不应该是单数吗

2022-06-06 17:11 UTC, ye-luo-xi-tui commented on rm_calibration_controllers/README.md
> +  When response to this server, it will return respond about whether target joint has been calibrated.
`response to this server`不觉得怪怪的吗。。我上面说的是你后面的respond。

2022-06-06 17:11 UTC, ye-luo-xi-tui commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +      halted = actuator_.getHalted();
这两句完全可以合成一句。

2022-06-07 00:53 UTC, qiayuanliao commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +      halted = actuator_.getHalted();
完全不需要 变量 halted 啊

2022-06-07 08:38 UTC, ljq-lv commented
halted是从电机反馈回来关于当前电机是否停止的信息

2022-06-07 09:21 UTC, qiayuanliao commented
> halted是从电机反馈回来关于当前电机是否停止的信息

傻逼，看代码啊！！

2022-06-07 12:39 UTC, ljq-lv commented
我是傻b 人晕了

2022-06-07 13:01 UTC, qiayuanliao requested changes

2022-06-07 13:01 UTC, qiayuanliao commented
@ye-luo-xi-tui help

2022-06-10 07:27 UTC, qiayuanliao commented
@ye-luo-xi-tui

2022-06-10 07:48 UTC, ye-luo-xi-tui commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +          countdown_ = 100;
有没有一种可能，其实不需要countdown？

2022-06-10 08:50 UTC, ljq-lv commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +          countdown_ = 100;
不要countdown的话 可能会导致在归位之前 认为该轴校准完毕 但实际上该轴还在归位的过程中

2022-06-10 15:38 UTC, qiayuanliao commented on rm_calibration_controllers/src/joint_calibration_controller.cpp
> +          countdown_ = 100;
不需要coutdown

2022-06-10 16:17 UTC, ye-luo-xi-tui commented
@qiayuanliao 这回应该是没问题了吧（我猜）

2022-06-10 16:21 UTC, merged