Modify the kinematics solution of omni-direction wheel.
rm-controls/rm_controllers pull request #79
Opened 2022-07-28 14:17 UTC by NaHCO3bc

修改了init部分和movejoint解算部分

2022-07-28 14:44 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/config/template_omni.yaml
> +                           [ -0.7071 , -0.7071 ] ] #[[cos,sin],[-sin,cos]] 3pi/4
建议是再斟酌一下叫什么名字

2022-07-28 14:45 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/include/rm_chassis_controllers/omni.h
> +#include <effort_controllers/joint_position_controller.h>
你include个`joint_position_controller`做什么？？？？？？？？？？？

2022-07-28 14:46 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/include/rm_chassis_controllers/omni.h
> +#include <effort_controllers/joint_position_controller.h>
你下面想要声明一个`JointVelocityController`对象的时候居然没报错？？？？？？？？

2022-07-28 14:55 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/config/template_omni.yaml
> +                           [ -0.7071 , -0.7071 ] ] #[[cos,sin],[-sin,cos]] 3pi/4
包括你代码里面

2022-07-28 14:58 UTC, NaHCO3bc commented on rm_chassis_controllers/config/template_omni.yaml
> +                           [ -0.7071 , -0.7071 ] ] #[[cos,sin],[-sin,cos]] 3pi/4
命名还在想，我也知道不太行😥

2022-07-28 14:58 UTC, NaHCO3bc commented on rm_chassis_controllers/include/rm_chassis_controllers/omni.h
> +#include <effort_controllers/joint_position_controller.h>
嘶可能是我打错了？好怪

2022-07-28 14:59 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/src/omni.cpp
> +    module.ctrl_wheel_->update(time, period);
不应该是这样吧，你正运动学想怎么搞

2022-07-28 15:00 UTC, ye-luo-xi-tui commented
话说仿真能跑通吗

2022-07-28 15:03 UTC, NaHCO3bc commented on rm_chassis_controllers/src/omni.cpp
> +    module.ctrl_wheel_->update(time, period);
就是想不出咋搞所以请求指导

2022-07-28 15:04 UTC, NaHCO3bc commented
> 话说仿真能跑通吗

平移和自转还真正常😥套了之前代码的正运动学公式验算过了

2022-07-28 15:10 UTC, ye-luo-xi-tui commented on rm_chassis_controllers/src/omni.cpp
> +    module.ctrl_wheel_->update(time, period);
把你所有的`module.h`拼成一个矩阵呀

2022-07-29 02:15 UTC, qiayuanliao requested changes

2022-07-29 02:15 UTC, qiayuanliao commented on rm_chassis_controllers/config/template_omni.yaml
> +                           [ -0.7071 , -0.7071 ] ] #[[cos,sin],[-sin,cos]] 3pi/4
你这是什么鸡巴，为什么在参数服务器里面写矩阵啊....我真的无语到了，其实就三个参数啊，你搞成12个参数干嘛？？？

2022-07-29 02:15 UTC, qiayuanliao commented on rm_chassis_controllers/include/rm_chassis_controllers/omni.h
> +  Vec3<double> chassis_vel_;
为什么需要是类成员变量？

2022-07-29 02:15 UTC, qiayuanliao commented on rm_chassis_controllers/include/rm_chassis_controllers/omni.h
> +  effort_controllers::JointVelocityController* ctrl_wheel_;
你到底带不带下划线？？？有的带有的不带

2022-07-29 04:17 UTC, closed without merging