Fix the bug that the shooter cannot be turned from push to ready.
rm-controls/rm_controllers pull request #93
Opened 2022-10-20 09:17 UTC by NaHCO3bc

修了步兵高射频情况下无法从push进ready的锅；步兵上表现为响应跟不上的情况下，主动降低频率，保持响应，因此无法达到20hz的高射频；在英雄上测试都正常

2022-10-20 09:37 UTC, ye-luo-xi-tui approved these changes

2022-10-22 11:39 UTC, ljq-lv approved these changes

2022-10-22 11:42 UTC, Aung-xiao approved these changes

2022-10-22 11:43 UTC, L-SY approved these changes

2022-10-22 11:52 UTC, 1moule approved these changes

2022-10-22 11:52 UTC, chenhuiYu00 approved these changes

2022-10-22 12:44 UTC, caijiefeng approved these changes

2022-10-22 13:19 UTC, qiayuanliao commented
啊这，修了个寂寞....那步兵高射频咋办？

2022-10-22 13:33 UTC, ye-luo-xi-tui commented
> 啊这，修了个寂寞....那步兵高射频咋办？

就算什么都不改，外部给了一个达不到的射频，拨盘响应跟不上就是达不到。现在只是在达不到这个射频的时候降低了射频。至于它响应跟不上那是机械应该解决的问题

2022-10-22 13:41 UTC, qiayuanliao commented
> 就算什么都不改，外部给了一个达不到的射频，拨盘响应跟不上就是达不到。现在只是在达不到这个射频的时候降低了射频。至于它响应跟不上那是机械应该解决的问题

**屁的机械问题**，现在达不到20hz射频的原因是**控制算法或逻辑有问题**，你这都能把锅甩到机械上？？？sb吧。

你直接用一个速度控制器让它以 20hz 对应的转速旋转，它是不是可以 20hz 发射？甚至30hz我觉得都没有问题！可以达到的话，为什么是机械的问题？我都不知道**你的脑子在想什么**哪来的自信能这么**理直气壮地**说是机械该解决的问题。

我之前已经跟你明确且不止一次地说过两个解决方案：
1. 复杂的：考虑轨迹，同时给期望位置和期望速度（现在的期望速度一直为零）
2. 简单的：分成两个模式，连续射击和单发射击。

你是不是已经**忘得无影无踪**了？

2022-10-22 15:32 UTC, ye-luo-xi-tui commented
> > 就算什么都不改，外部给了一个达不到的射频，拨盘响应跟不上就是达不到。现在只是在达不到这个射频的时候降低了射频。至于它响应跟不上那是机械应该解决的问题
> 
> **屁的机械问题**，现在达不到20hz射频的原因是**控制算法或逻辑有问题**，你这都能把锅甩到机械上？？？sb吧。
> 
> 你直接用一个速度控制器让它以 20hz 对应的转速旋转，它是不是可以 20hz 发射？甚至30hz我觉得都没有问题！可以达到的话，为什么是机械的问题？我都不知道**你的脑子在想什么**哪来的自信能这么**理直气壮地**说是机械该解决的问题。
> 
> 我之前已经跟你明确且不止一次地说过两个解决方案：
> 
>     1. 复杂的：考虑轨迹，同时给期望位置和期望速度（现在的期望速度一直为零）
> 
>     2. 简单的：分成两个模式，连续射击和单发射击。
> 
> 
> 你是不是已经**忘得无影无踪**了？

1、5号和3号用相同的代码，一个能停下来，一个停不下来。说明**在相同的控制算法或逻辑下5号拨盘响应比3号快**，机械上**至少是一个可以优化的方向**。
2、刚才经过测试这个版本的代码也能达到20hz，和旧版本差别不大。我提出可能达不到20hz的猜测，苏柏承则改成了肯定句。
3、你提出的复杂的解决方案可能会是未来一段时间的最优解。至于简单的，我确实忘记了连续射击具体怎么实现。
4、没有人愿意和恶语伤人的人合作，衷心祝愿您永远不会犯错。

2022-10-22 15:38 UTC, ye-luo-xi-tui commented
5、这个解决方案同样足够简单，且在测试中同样达到了20hz的高射频。在未来探索更好的控制算法之前，解决这个bug的需求非常迫切。

2022-10-22 15:56 UTC, qiayuanliao commented
> 1、5号和3号用相同的代码，一个能停下来，一个停不下来。说明**在相同的控制算法或逻辑下5号拨盘响应比3号快**，机械上**至少是一个可以优化的方向**。 2、刚才经过测试这个版本的代码也能达到20hz，和旧版本差别不大。我提出可能达不到20hz的猜测，苏柏承则改成了肯定句。 3、你提出的复杂的解决方案可能会是未来一段时间的最优解。至于简单的，我确实忘记了连续射击具体怎么实现。 4、没有人愿意和恶语伤人的人合作，衷心祝愿您永远不会犯错。

- 简单解决方法还需要我告诉你具体如何实现吗？这完全是你能思考得到的啊。
    1. 连续发射的模式下给位置递增，同时给对应的恒定速度期望；
    2. 退出连续发射模式时记得 normalize。
   
- 这个问题和解决方案我跟你说了两到三次了（暑假时必有一次，暑假后必有一次），结果你用了一个莫名其妙的方法，并且丝毫没有提及我之前说的方法，难道不恼人吗？
- 事实是我强忍着不自己上手改，费心费力地向你说明，然后你一般不给是否听懂的反馈，最后隔了几个月后给我一份看起来莫名其妙的答卷。这是你说的合作嘛？
- 以你的水平我更想称之为指导。无论是合作还是指导，至少你要听懂和记住大部分我们说的话吧？我实在不清楚你在搞这个pr时还记得我们讨论过什么内容，以至于你能一句话也不提+改出这个结果。
- 这个bug你无视了几个月？你现在说非常迫切哈哈哈哈哈哈哈哈哈哈，真的笑死我。

2022-10-23 02:43 UTC, ye-luo-xi-tui commented
该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听

2022-10-23 03:05 UTC, qiayuanliao commented
> 该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听

可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数。

另外我不确定现在这么写会不会导致有时候即打不出弹，有没有可能出现稍微卡住后即没有触发堵转也没有在允许误差内？

2022-10-29 02:59 UTC, qiayuanliao commented
> > 该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听
> 
> 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数。
> 
> 另外我不确定现在这么写会不会导致有时候即打不出弹，有没有可能出现稍微卡住后即没有触发堵转也没有在允许误差内？

@ye-luo-xi-tui 这个咋说

2022-10-29 03:01 UTC, ye-luo-xi-tui commented
> > > 该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听
> > 
> > 
> > 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数。
> > 另外我不确定现在这么写会不会导致有时候即打不出弹，有没有可能出现稍微卡住后即没有触发堵转也没有在允许误差内？
> 
> @ye-luo-xi-tui 这个咋说

我让他确定会不会有打不出弹的问题，他最近考试基本没进度

2022-10-31 06:44 UTC, caijiefeng approved these changes

2022-11-02 07:53 UTC, NaHCO3bc commented
> > > > 该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听
> > > 
> > > 
> > > 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数。
> > > 另外我不确定现在这么写会不会导致有时候即打不出弹，有没有可能出现稍微卡住后即没有触发堵转也没有在允许误差内？
> > 
> > 
> > @ye-luo-xi-tui 这个咋说
> 
> 我让他确定会不会有打不出弹的问题，他最近考试基本没进度

我尝试将拨盘的pid调差使得响应变差，会出现拨盘发生卡弹但没有进入block且不在允许误差范围内，一直在push模式下

2022-11-03 02:46 UTC, qiayuanliao commented
> > > > > 该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听
> > > > 
> > > > 
> > > > 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数。
> > > > 另外我不确定现在这么写会不会导致有时候即打不出弹，有没有可能出现稍微卡住后即没有触发堵转也没有在允许误差内？
> > > 
> > > 
> > > @ye-luo-xi-tui 这个咋说
> > 
> > 
> > 我让他确定会不会有打不出弹的问题，他最近考试基本没进度
> 
> 我尝试将拨盘的pid调差使得响应变差，会出现拨盘发生卡弹但没有进入block且不在允许误差范围内，一直在push模式下

确实理应出现这样。参数化还没搞？

2022-11-03 03:02 UTC, NaHCO3bc commented
> > > > > > 该说的在微信都已经说过了，这个pr你合不合并随你便吧。有其他意见我洗耳恭听
> > > > > 
> > > > > 
> > > > > 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数。
> > > > > 另外我不确定现在这么写会不会导致有时候即打不出弹，有没有可能出现稍微卡住后即没有触发堵转也没有在允许误差内？
> > > > 
> > > > 
> > > > @ye-luo-xi-tui 这个咋说
> > > 
> > > 
> > > 我让他确定会不会有打不出弹的问题，他最近考试基本没进度
> > 
> > 
> > 我尝试将拨盘的pid调差使得响应变差，会出现拨盘发生卡弹但没有进入block且不在允许误差范围内，一直在push模式下
> 
> 确实理应出现这样。参数化还没搞？

搞了，我push一下

2022-11-03 12:49 UTC, qiayuanliao requested changes
改成 xxx_threshold 好点，而且我记得有两个参数吧？

2022-11-03 12:49 UTC, qiayuanliao commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
应该放在上一行那些参数里面吧，58行的都是速度

2022-11-03 12:53 UTC, qiayuanliao commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
> 有两个参数
> 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数

为什么又无视我说的话？？？？？
两件事情都被你们无视了：
1. 把代码里面两个 `0.01` 参数化，你现在 L95 依旧是直接写的 `0.01`
2. 我不确定退出和进入这两个参数要不要都用一个值，然后 config 里面就只写一个 @ye-luo-xi-tui 。

2022-11-03 12:58 UTC, NaHCO3bc commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
L95那里是我改漏了，傍晚才发现；两个参数的话我没想清楚另一个怎么用之前就没写到

2022-11-03 12:58 UTC, NaHCO3bc commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
> > 有两个参数
> > 可以合并，但是有退出和进入PUSH两个参数（现在均为0.01) 需要参数化，我不确定是否需要分开两个参数
> 
> 为什么又无视我说的话？？？？？ 两件事情都被你们无视了：
> 
> 1. 把代码里面两个 `0.01` 参数化，你现在 L95 依旧是直接写的 `0.01`
> 2. 我不确定退出和进入这两个参数要不要都用一个值，然后 config 里面就只写一个 @ye-luo-xi-tui 。

L95那里是我改漏了，傍晚才发现；两个参数的话我没想清楚另一个怎么用之前就没写到

2022-11-03 13:19 UTC, qiayuanliao commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
> 两个参数的话我没想清楚另一个怎么用之前就没写到

找你组长讨论啊，然后写清楚告诉我啊，你搞一半给我看什么。

2022-11-04 08:06 UTC, NaHCO3bc commented
我尝试修改进入参数和退出参数的大小关系进行比较：
1.当进入的参数为0.01，退出的为0.02时，发射效果和两者都为0.01差别不大，但可以在无法发射且不进入block的情况会能回到ready
2.当进入的参数大于退出的参数时，就会影响发射效果了：进入0.02，退出0.01时会导致有出现双发的情况；进入0.03，退出0.01时我感觉像是射频上不去，一直在单发
综上我认为可以将退出的参数修改为比进入的参数稍大，例如0.02，这样至少在逻辑上可以使它可以从push转换到ready，而不会因为误差大，导致出现无法发射且不进入block又无法切换回ready的情况。

2022-11-04 08:09 UTC, NaHCO3bc commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
> > 两个参数的话我没想清楚另一个怎么用之前就没写到
> 
> 找你组长讨论，然后写清楚告诉我啊，你搞一半给我看啥。

我尝试修改进入参数和退出参数的大小关系进行比较：
1.当进入的参数为0.01，退出的为0.02时，发射效果和两者都为0.01差别不大，但可以在无法发射且不进入block的情况会能回到ready
2.当进入的参数大于退出的参数时，就会影响发射效果了：进入0.02，退出0.01时会导致有出现双发的情况；进入0.03，退出0.01时我感觉像是射频上不去，一直在单发
综上我认为可以将退出的参数修改为比进入的参数稍大，例如0.02，这样至少在逻辑上可以使它可以从push转换到ready，而不会因为误差大，导致出现无法发射且不进入block又无法切换回ready的情况。

2022-11-04 08:44 UTC, ye-luo-xi-tui commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
> > > 两个参数的话我没想清楚另一个怎么用之前就没写到
> > 
> > 
> > 找你组长讨论，然后写清楚告诉我啊，你搞一半给我看啥。
> 
> 我尝试修改进入参数和退出参数的大小关系进行比较： 1.当进入的参数为0.01，退出的为0.02时，发射效果和两者都为0.01差别不大，但可以在无法发射且不进入block的情况会能回到ready 2.当进入的参数大于退出的参数时，就会影响发射效果了：进入0.02，退出0.01时会导致有出现双发的情况；进入0.03，退出0.01时我感觉像是射频上不去，一直在单发 综上我认为可以将退出的参数修改为比进入的参数稍大，例如0.02，这样至少在逻辑上可以使它可以从push转换到ready，而不会因为误差大，导致出现无法发射且不进入block又无法切换回ready的情况。

说是进入不太对吧，难道不是一个使期望位置向前一个拨差的阈值吗？

2022-11-04 08:47 UTC, ye-luo-xi-tui commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
话说它发射不了应该是堵转了？进了ready它能转到位吗？

2022-11-04 08:53 UTC, NaHCO3bc commented on rm_shooter_controllers/include/rm_shooter_controllers/standard.h
> +  double pos_diff, qd_10, qd_15, qd_16, qd_18, qd_30, lf_extra_rotat_speed;
> 话说它发射不了应该是堵转了？进了ready它能转到位吗？

就pid调差一些之后，电机力不够就会在稍微卡一点的情况下不发射了，进ready也不能转到位，但把pid调回原先的值就可以继续发。

2022-11-09 06:00 UTC, qiayuanliao approved these changes

2022-11-10 09:56 UTC, NaHCO3bc commented
误差大于参数值时无法push且无法进入block时：

1. 不push且不进block时，trigger的力矩会偏小，小于block_effort，这个情况下即使把pid调得很极限，也无法使力矩到达进入block的需求值。
2. 如果修改block_effort也无法得到改善，出现误差值会趋于允许范围但仍然无法满足发射条件，此时trigger的力矩同样会很小，绝对值远小于block_effort，单纯修改block_effort无法满足需求。

因此我尝试在push和进block的逻辑上进行修改，只要把pid调得比较良好，最新的这个commit是可以比较丝滑的发射并且能正常进入block并解决不push且不进block的问题。
如果pid调得不好就可能会因为物理卡弹而停留在block mode里

2022-11-12 13:58 UTC, qiayuanliao approved these changes
有道理！

2022-11-16 06:31 UTC, merged